### ISSUE TITLE
What is the license of this project?

### ISSUE THREAD

**Issue by protox** [lucassene/CapsuleWars#1]
Was curious what the license of the code is, I don't seem to see anything in the readme file, and if others can use it for their own projects. Very cool work by the way.

Thanks.

**Comment by lucassene** [comment]
Hello @protox,
Firstly, thanks to your feedback, I am really happy to see my work is reaching people and interesting them. And thank you as well, for bringing this issue to my attention. I've already updated the readme adding the license information. You are free to use and modify the code you find in this repository in your study and personal projects, but not commercially.
Kind regards,
Lucas Sene

**Comment by protox** [comment]
Alright thanks for the update.
