### ISSUE TITLE
Missing dependencies / Load errors / etc.

### ISSUE THREAD

**Issue by m1zukash1** [lucassene/CapsuleWars#2]
![image](https://user-images.githubusercontent.com/75336116/113489272-026eff00-94cc-11eb-993c-09522677f024.png)

**Comment by m1zukash1** [comment]
Just downloaded source from github, cuz I didn't like the fps cap and was prompted with missing dependencies, load errors, etc.

**Comment by lucassene** [comment]
Thanks @m1zukash1 to bring this to my attention. I did indeed not include some assets (such as textures, fonts, audio, etc) in the source project. But I just checked and I can share them for private purposes, so I will make a commit soon, including all these items. Alternatively, you can use the current code just by putting some textures in the assets/textures folder with the same names shown in the error messages.

**Comment by lucassene** [comment]
Done @m1zukash1 ! Now you should not have any broken dependencies, as every asset used by the project is included.

**Comment by m1zukash1** [comment]
Works without problems now
